In [78]:
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# **Import and Process the data**

In [79]:
# Import data
path = '/content/drive/My Drive/Colab Notebooks/Udemy_Complete Machine Learning and Data Science/AoC/Day 2/' # create path to call file(s) in my directory 
inputs = pd.read_csv(path+'input.txt', header = None) # create a dataframe of the input data
inputs

             0
0    forward 6
1    forward 6
2       down 6
3       down 5
4         up 2
..         ...
995       up 4
996       up 4
997  forward 8
998  forward 1
999  forward 2

[1000 rows x 1 columns]

In [80]:
# Split data into two collumns called Directions and Quantity
inputs[['Directions','Quantity']]= inputs[0].str.split(" ", n = 2, expand = True)
inputs = inputs.drop(columns=0)
inputs.head(10)

  Directions Quantity
0    forward        6
1    forward        6
2       down        6
3       down        5
4         up        2
5    forward        4
6    forward        8
7         up        9
8    forward        3
9       down        1

In [81]:
inputs.dtypes # Show the data types of each column

Directions    object
Quantity      object
dtype: object

In [82]:
# Change type of a Quantity column from object to int type in order to be able to calculate them
inputs['Quantity'] = inputs['Quantity'].astype(int)

In [83]:
inputs.dtypes

Directions    object
Quantity       int64
dtype: object

# **Part 1**

In [84]:
forward = 0
depth = 0

for i in range(len(inputs)): 
  if i == 1000: 
    break
  elif inputs.loc[i][0] == 'forward':
    forward += inputs.loc[i][1]
  elif inputs.loc[i][0] == 'up':
    depth -= inputs.loc[i][1]
  elif inputs.loc[i][0] == 'down':
    depth += inputs.loc[i][1]

print('Total forward =', forward)
print('Total depth =', depth)
result = forward*depth
print('Result of the total forward multiplied by the total depth =', result)

Total forward = 1988
Total depth = 913
Result of the total forward multiplied by the total depth = 1815044

# **Part 2**

In [85]:
forward = 0
aim = 0
depth = 0

for i in range(len(inputs)): #range(6)
  if i == 1000: 
    break
  elif inputs.loc[i][0] == 'forward':
    forward += inputs.loc[i][1]
    depth += aim*inputs.loc[i][1]
  elif inputs.loc[i][0] == 'up':
    aim -= inputs.loc[i][1]
  elif inputs.loc[i][0] == 'down':
    aim += inputs.loc[i][1]

print('Total forward =', forward)
print('Total depth =', depth)
result = forward*depth
print('Result of the total forward multiplied by the total depth =', result)

Total forward = 1988
Total depth = 874891
Result of the total forward multiplied by the total depth = 1739283308